app/data_input/__init__.py
# app/data_input/__init__py
from flask import Blueprint

data_input_bp = Blueprint('data_input', __name__)

app/data_input/routes.py
# C:\Users\Peter\Blueprint\app\data_input\routes.py
from flask import render_template, session, request, redirect, url_for, flash, jsonify
from app.data_input import data_input_bp
from app.db_connection.conn import get_connection
from datetime import datetime, timezone
from app.auth.decorators import require_valid_staff_initials

uk_timestamp = datetime.now(timezone.utc).astimezone()

import speech_recognition as sr


@data_input_bp.route('/process_audio', methods=['POST'])
def process_audio():
    audio_file = request.files['audio']
    # Assuming voice_to_text.py has a function `transcribe_audio` to process the audio file
    from SpeechRecog.voice_to_text import transcribe_audio
    recognized_text = transcribe_audio(audio_file)
    return jsonify({'recognized_text': recognized_text})



# Collect data for Unit and Service
@data_input_bp.route('/collect_data', methods=['GET', 'POST'])
def collect_data():
    conn=get_connection()
    with conn.cursor() as cursor:
        cursor.execute("SELECT DISTINCT unit_name FROM unit_list ORDER BY unit_name")
        units = [row[0] for row in cursor.fetchall()]
        cursor.execute("SELECT service_name FROM service_list")
        services = [row[0] for row in cursor.fetchall()]
    conn.close()
    return render_template('collect_data.html', units=units, services=services)

# API endpoint to fetch residents dynamically
@data_input_bp.route('/get_residents', methods = ['POST'])
def get_residents():
    unit = request.json.get('unit')
    conn = get_connection()
    with conn.cursor() as cursor:
        # fetch resident initials where resident_unit matches the selected unit
        query = ("SELECT resident_initials FROM resident_list WHERE resident_unit = %s")
        cursor.execute(query, (unit,))
        residents = [row[0] for row in cursor.fetchall()]
    conn.close()
    return jsonify(residents=residents)

# Data input logic
@data_input_bp.route('/data_input_logic', methods=['POST'])
def data_input_logic():
    unit_name = request.form.get('unit_name')
    resident_initials = request.form.get('resident_initials')
    service_name = request.form.get('service_name')
    if service_name == 'fluid intake':
        return redirect(url_for('data_input.fluid_intake', 
                            unit_name=unit_name, 
                            resident_initials=resident_initials))
    if service_name == 'food intake':
        return redirect(url_for('data_input.food_intake', 
                            unit_name=unit_name, 
                            resident_initials=resident_initials))
    if service_name == 'personal care':
        return redirect(url_for('data_input.personal_care_input', 
                            unit_name=unit_name, 
                            resident_initials=resident_initials))
    if service_name == 'cardex':
        return redirect(url_for('data_input.cardex_input', 
                            unit_name=unit_name, 
                            resident_initials=resident_initials))
        
    if service_name == 'care frequency':
        return redirect(url_for('data_input.care_frequency', 
                            unit_name=unit_name, 
                            resident_initials=resident_initials))

    else:
        return render_template('under_construction.html')

# Fluid intake     
@data_input_bp.route('/fluid_intake')
def fluid_intake():
    unit_name = request.args.get('unit_name')
    resident_initials = request.args.get('resident_initials')
    
    conn = get_connection()
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT DISTINCT fluid_name FROM fluid_list ORDER BY fluid_name 
        """)
        fluid_list = [row[0] for row in cursor.fetchall()]
    conn.close()
    
    return render_template('fluid_intake.html',
                        fluid_list=fluid_list, 
                        unit_name=unit_name,
                        resident_initials=resident_initials)

# Submit fluid intake
@require_valid_staff_initials
@data_input_bp.route('/submit_fluid_intake', methods=['POST'])
def submit_fluid_intake():
    conn = None
    try:
        conn = get_connection()
        with conn.cursor() as cursor:
            # Get form data
            input_time = request.form.get('input_time')
            #timestamp = datetime.strptime(input_time, '%Y-%m-%d %H:%M').time()
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
            fluid_name = request.form.get('fluid_name')
            fluid_volume = request.form.get('fluid_volume')
            fluid_note = request.form.get('fluid_note')
            staff_initials = request.form.get('staff_initials')
            resident_initials = request.form.get('resident_initials')

            
            # Insert data
            cursor.execute("""
                INSERT INTO fluid_chart 
                (timestamp, resident_initials, fluid_name, fluid_volume, fluid_note, staff_initials)
                VALUES (%s, %s, %s, %s, %s, %s)
                """, (timestamp, resident_initials, fluid_name, fluid_volume, fluid_note, staff_initials))
            
            conn.commit()
            flash('Data updated successfully', 'success')
            return redirect(url_for('data_input.collect_data'))
            
    except Exception as e:
        if conn is not None:
            conn.rollback()
        flash(f'Error: {str(e)}', 'error')
        return redirect(url_for('data_input.fluid_intake'))
    finally:
        if conn is not None:
            conn.close()

# Food intake            
@data_input_bp.route('/food_intake')
def food_intake():
    unit_name = request.args.get('unit_name')
    resident_initials = request.args.get('resident_initials')
    
    conn = get_connection()
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT DISTINCT food_name FROM food_list ORDER BY food_name 
        """)
        food_list = [row[0] for row in cursor.fetchall()]
    conn.close()
    
    return render_template('food_intake_form.html', food_list=food_list, unit_name=unit_name, resident_initials=resident_initials)

# Submit food intake
@data_input_bp.route('/submit_food_intake', methods=['POST'])
@require_valid_staff_initials
def submit_food_intake():
    unit_name = request.args.get('unit_name')
    resident_initials = request.form.get('resident_initials')
    food_name = request.form.get('food_name')  # Updated variable name
    food_volume = request.form.get('food_volume')
    food_note = request.form.get('food_note')
    input_time = request.form.get('input_time')  # Retrieve input_time from the form data
    staff_initials = request.form.get('staff_initials').upper()  # Convert to uppercase
    timestamp = datetime.now().strftime('%Y-%m-%d') + ' ' + input_time # + ':00'

    conn = get_connection()
    with conn.cursor() as cursor:
        cursor = conn.cursor()

        cursor.execute('''
            INSERT INTO food_chart (timestamp, resident_initials, food_name, food_amount, food_note, staff_initials)
            VALUES (%s, %s, %s, %s, %s, %s)
        ''', (timestamp, resident_initials,food_name, food_volume, food_note, staff_initials))
        conn.commit()
        conn.close()

    flash('Food intake recorded successfully!', 'success')
    return redirect(url_for('data_input.food_intake', unit_name=unit_name, resident_initials=resident_initials))

# Personal care input
@data_input_bp.route('/personal_care_input')
def personal_care_input():
    unit_name = request.args.get('unit_name')
    resident_initials = request.args.get('resident_initials')
    conn = get_connection()
    with conn.cursor() as cursor:
        cursor.execute('SELECT DISTINCT personal_care_name FROM personal_care_list ORDER BY personal_care_name')

        personal_care_list = [row[0] for row in cursor.fetchall()]
    conn.close()
    return render_template('personal_care_form.html', personal_care_list= personal_care_list, unit_name=unit_name, resident_initials=resident_initials)

# Personal care submit
@data_input_bp.route('/submit_personal_care', methods=['POST'])
@require_valid_staff_initials
def submit_personal_care():
    unit_name = request.form.get('unit_name')
    resident_initials = request.form.get('resident_initials')
    personal_care_type = request.form.get('personal_care_type')
    personal_care_note = request.form.get('personal_care_note')
    personal_care_duration = request.form.get('personal_care_duration')
    input_time = request.form.get('input_time')
    staff_initials = request.form.get('staff_initials').upper()
    timestamp = datetime.now().strftime('%Y-%m-%d') + ' ' + input_time # + ':00'

    conn = get_connection()
    with conn.cursor() as cursor:
        cursor.execute('''
        INSERT INTO personal_care_chart (resident_initials, timestamp, personal_care_type, personal_care_note, personal_care_duration, staff_initials)
        VALUES (%s, %s, %s, %s, %s, %s)
    ''', (resident_initials, timestamp, personal_care_type, personal_care_note, personal_care_duration,staff_initials))
    conn.commit()
    conn.close()

    flash('Personal care entry recorded successfully!', 'success')
    return redirect(url_for('data_input.personal_care_input', unit_name=unit_name, resident_initials=resident_initials))

# Kardex input
@data_input_bp.route('/cardex_input')
def cardex_input():
    unit_name = request.args.get('unit_name')
    resident_initials = request.args.get('resident_initials')
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT id, cardex_text FROM cardex_chart')
    cardex_text = cursor.fetchall()
    conn.close()
    return render_template('cardex_form.html', cardex_text=cardex_text, unit_name=unit_name, resident_initials=resident_initials)


# Kardex submit
@data_input_bp.route('/submit_cardex', methods=['POST'])
@require_valid_staff_initials
def submit_cardex():
    resident_initials = request.form.get('resident_initials')
    cardex_text = request.form.get('cardex_text')

app/login/__init__.py
# app/login/__init__.py
from flask import Blueprint

login_bp = Blueprint('login', __name__)

app/login/routes.py
from flask import render_template
from app.login import login_bp
from app.db_connection.conn import get_connection

@login_bp.route('/login')
def login():  
    return render_template('login.html')

@login_bp.route('/register')
def register():
    return render_template('register.html')

@login_bp.route('/logout')
def logout():
    return render_template('logout.html')

app/templates/admin_menu.html
{% extends "base.html" %}

{% block content %}

<body>
    <h2>Admin Menu</h2>
    {{ session.username }}
</body>
{% endblock%}

app/templates/cardex_form.html
{% extends "base.html" %}

{% block content %}
    <h2>Cardex Form</h2>
    <form method="POST" action="{{ url_for('data_input.submit_cardex') }}" class="form-container">
        <input type="hidden" name="unit_name" value="{{ request.args.get('unit_name') }}">
        <input type="hidden" name="resident_initials" value="{{ request.args.get('resident_initials') }}">
        <div class="form-group">
            <label for="cardex_text">Cardex Text:</label>
            <textarea id="cardex_text" name="cardex_text" required></textarea>
            <button type="button" onclick="startRecognition()">Start Speech Recognition</button>
            <button type="button" onclick="stopRecognition()">Stop Speech Recognition</button>
        </div>
        <div class="form-group">
            <label for="input_time">Time of Input:</label>
            <input type="time" id="input_time" name="input_time" required>
        </div>
        <div class="form-group">
            <label for="staff_initials">Staff Initials:</label>
            <input type="text" id="staff_initials" name="staff_initials" required>
        </div>
        
        <button type="submit">Submit</button>
    </form>
    
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const now = new Date();
            const hours = String(now.getHours()).padStart(2, '0');
            const minutes = String(now.getMinutes()).padStart(2, '0');
            document.getElementById('input_time').value = `${hours}:${minutes}`;
        });

        let recognition;

        function sendAudioData(audioBlob) {
            const formData = new FormData();
            formData.append('audio', audioBlob, 'recording.wav');

            fetch('/process_audio', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('cardex_text').value = data.recognized_text;
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        }

        // Improved speech recognition function
        function startRecognition() {
            recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
            recognition.lang = 'en-US';
            recognition.interimResults = false;
            recognition.maxAlternatives = 1;
            recognition.continuous = true; // Enable continuous recognition
            
            recognition.start();

            recognition.onresult = (event) => {
                const speechResult = event.results[event.results.length - 1][0].transcript;
                // Append new text instead of replacing
                document.getElementById('cardex_text').value += ' ' + speechResult;
                const audioBlob = new Blob([speechResult], { type: 'audio/wav' });
                sendAudioData(audioBlob);
            };

            recognition.onend = () => {
                // Automatically restart recognition when it ends
                recognition.start();
            };

            recognition.onerror = (event) => {
                console.error('Speech recognition error detected: ' + event.error);
                if (event.error !== 'no-speech') {
                    recognition.start();
                }
            };
        }

        // Function to stop speech recognition
        function stopRecognition() {
            if (recognition) {
                recognition.stop();
            }
        }
    </script>
{% endblock %}

app/templates/care_frequency_form.html
<!-- c:/Users/Peter/Documents/Care-Home-4/app/templates/care_frequency_form.html -->
{% extends "base.html" %}

{% block content %}
<h2>Care Frequency Data Collection</h2>
<h3>for {{resident_initials}} </h3>
<form method="POST" action="{{ url_for('data_input.submit_care_frequency') }}" class="form-container">

    <input type="hidden" name="resident_initials" value="{{ request.args.get('resident_initials') }}">

    <div class="form-group">
        <label for="position"><strong>Position:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="position_right" name="position" value="Right" onclick="singleSelect(this)">
            <label for="position_right">Right</label>
            <input type="checkbox" id="position_left" name="position" value="Left" onclick="singleSelect(this)">
            <label for="position_left">Left</label>
            <input type="checkbox" id="position_back" name="position" value="Back" onclick="singleSelect(this)">
            <label for="position_back">Back</label>
            <input type="checkbox" id="position_chair" name="position" value="Chair" onclick="singleSelect(this)">
            <label for="position_chair">Chair</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="mattress_appropriate"><strong>Mattress Appropriate:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="mattress_appropriate_yes" name="mattress_appropriate" value="yes" onclick="singleSelect(this)">
            <label for="mattress_appropriate_yes">Yes</label>
            <input type="checkbox" id="mattress_appropriate_no" name="mattress_appropriate" value="no" onclick="singleSelect(this)">
            <label for="mattress_appropriate_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="cushion_appropriate"><strong>Cushion Appropriate:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="cushion_appropriate_yes" name="cushion_appropriate" value="yes" onclick="singleSelect(this)">
            <label for="cushion_appropriate_yes">Yes</label>
            <input type="checkbox" id="cushion_appropriate_no" name="cushion_appropriate" value="no" onclick="singleSelect(this)">
            <label for="cushion_appropriate_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="functionality_check"><strong>Functionality Check:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="functionality_check_yes" name="functionality_check" value="yes" onclick="singleSelect(this)">
            <label for="functionality_check_yes">Yes</label>
            <input type="checkbox" id="functionality_check_no" name="functionality_check" value="no" onclick="singleSelect(this)">
            <label for="functionality_check_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="pressure_areas_checked"><strong>Pressure Areas Checked:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="pressure_areas_checked_yes" name="pressure_areas_checked" value="yes" onclick="singleSelect(this)">
            <label for="pressure_areas_checked_yes">Yes</label>
            <input type="checkbox" id="pressure_areas_checked_no" name="pressure_areas_checked" value="no" onclick="singleSelect(this)">
            <label for="pressure_areas_checked_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="redness_present"><strong>Redness Present:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="redness_present_yes" name="redness_present" value="yes" onclick="singleSelect(this)">
            <label for="redness_present_yes">Yes</label>
            <input type="checkbox" id="redness_present_no" name="redness_present" value="no" onclick="singleSelect(this)">
            <label for="redness_present_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="incontinence_urine"><strong>Incontinence Urine:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="incontinence_urine_yes" name="incontinence_urine" value="yes" onclick="singleSelect(this)">
            <label for="incontinence_urine_yes">Yes</label>
            <input type="checkbox" id="incontinence_urine_no" name="incontinence_urine" value="no" onclick="singleSelect(this)">
            <label for="incontinence_urine_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="incontinence_bowels"><strong>Incontinence Bowels:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="incontinence_bowels_yes" name="incontinence_bowels" value="yes" onclick="singleSelect(this)">
            <label for="incontinence_bowels_yes">Yes</label>
            <input type="checkbox" id="incontinence_bowels_no" name="incontinence_bowels" value="no" onclick="singleSelect(this)">
            <label for="incontinence_bowels_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="diet_intake"><strong>Diet Intake:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="diet_intake_yes" name="diet_intake" value="yes" onclick="singleSelect(this)">
            <label for="diet_intake_yes">Yes</label>
            <input type="checkbox" id="diet_intake_no" name="diet_intake" value="no" onclick="singleSelect(this)">
            <label for="diet_intake_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="fluid_intake"><strong>Fluid Intake:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="fluid_intake_yes" name="fluid_intake" value="yes" onclick="singleSelect(this)">
            <label for="fluid_intake_yes">Yes</label>
            <input type="checkbox" id="fluid_intake_no" name="fluid_intake" value="no" onclick="singleSelect(this)">
            <label for="fluid_intake_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="supplement_intake"><strong>Supplement Intake:</strong></label>
        <div class="checkbox-group">
            <input type="checkbox" id="supplement_intake_yes" name="supplement_intake" value="yes" onclick="singleSelect(this)">
            <label for="supplement_intake_yes">Yes</label>
            <input type="checkbox" id="supplement_intake_no" name="supplement_intake" value="no" onclick="singleSelect(this)">
            <label for="supplement_intake_no">No</label>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <label for="notes"><strong>Notes:</strong></label>
        <input type="text" id="snotes" name="notes">
    </div>
    <hr>
    <div class="form-group">
        <label for="staff_initials"><strong>Staff Initials:</strong></label>
        <input type="text" id="staff_initials" name="staff_initials" required>
    </div>
        
    <button type="submit">Submit</button>
</form>

<style>
    .checkbox-group {
        display: flex;
        align-items: left;
    }
    .checkbox-group input[type="checkbox"] {
        margin-right: 3px;
    }
    .checkbox-group label {
        margin-right: 10px;
    }
</style>

<script>
function singleSelect(checkbox) {
    const checkboxes = document.getElementsByName(checkbox.name);
    checkboxes.forEach((item) => {
        if (item !== checkbox) item.checked = false;
    });
}
</script>
{% endblock %}

app/templates/carer_menu.html
{% extends "base.html" %}
{% block content %}

<div class = "container">
    <h2 class = "center-text">Menu</h2>

    <ul class="menu-list">
        <li><a href="{{ url_for('data_input.collect_data') }}" class="menu-item">Data collection</a></li>
        <li><a href="{{ url_for('data_output.report_selection') }}" class="menu-item">Report data</a></li>
        <!-- <li><a href="#" class="menu-item">Reports</a></li> -->
    </ul>

</div>
{% endblock%}   

app/templates/collect_data.html
<!-- Collect_data.html -->
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h2 class = "center-text" >Data Input</h2>
    <form method="POST" action="{{url_for('data_input.data_input_logic')}}" class="form-container">

    <div class = "form-group">
        <!-- Unit Dropdown -->
        <label for="unit">Select Unit:</label>
        <select id="unit" name="unit_name">
            <option value="">--Select Unit--</option>
            {% for unit in units %}
                <option value="{{ unit }}">{{ unit }}</option>
            {% endfor %}
        </select>

        <!-- Resident Dropdown -->
        <label for="resident">Select Resident:</label>
        <select id="resident" name="resident_initials">
        </select>

        <!-- Service Dropdown -->
        <label for = "service" > Select Service: </label>
        <select id = "service" name = "service_name">
            <option value = "" > -- Select Service -- </option>
            {% for service in services %}
                <option value="{{ service }}">{{ service }}</option>
            {% endfor %}
        </select>



    </div>

        <button type="submit">Submit</button>
    </form>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Get references to dropdowns
            const unitDropdown = document.getElementById('unit');
            const residentDropdown = document.getElementById('resident');

            // Event listener for unit selection
            unitDropdown.addEventListener('change', function () {
                const selectedUnit = unitDropdown.value;

                // Clear the resident dropdown
                residentDropdown.innerHTML = '<option value="">--Select Resident--</option>';

                if (selectedUnit) {
                    // Fetch residents for the selected unit
                    fetch('/get_residents', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({ unit: selectedUnit })
                    })
                    .then(response => response.json())
                    .then(data => {
                        // Populate the resident dropdown with the fetched data
                        data.residents.forEach(function (resident) {
                            const option = document.createElement('option');
                            option.value = resident;
                            option.textContent = resident;
                            residentDropdown.appendChild(option);
                        });
                    })
                    .catch(error => {
                        console.error('Error fetching residents:', error);
                    });
                }
            });
        });
    </script>
{% endblock %}

app/templates/data_input.html
{% extends "base.html" %}

{% block content %}

<body>
    <h2>Data Input</h2>
    {{ session.username }}
</body>
{% endblock%}

app/templates/here.html
{% extends 'base.html'%}

{% block content%}

<h2> Here </h2>

{% endblock%}

app/templates/report_fluid.html
<!-- c:/Users/Peter/Documents/Care-Home-4/app/templates/report_fluid.html -->
{% extends "base.html" %}

{% block content %}
<h2>Report Fluid</h2>
<h4> for {{ resident_initials }} from {{ start_date }} to {{ end_date }}</h4>
<hr>
    <table class= "table table-striped">
        <thead>
            <tr>
                <!--<th>Resident</th> -->
                <th>Date/Time</th>
                <th>Fluid</th>
                <th>Volume (ml)</th>
                <th>Note</th>
                <th>Staff Initials</th> <!-- New column header -->
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
                <tr>
                    
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td> <!-- New data cell -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('carer.carer_menu', unit_name=unit_name, resident_initials=resident_initials) }}" class="btn-dark-green">Back to Menu</a>
{% endblock %}

app/templates/report_food.html
<!-- c:/Users/Peter/Documents/Care-Home-4/app/templates/report_food.html -->
{% extends "base.html" %}

{% block content %}
    <h3>Report Food Intake</h3>
    <h4> for {{ resident_initials }} from {{ start_date }} to {{ end_date }}</h4>
    <hr>
    <table>
        <thead>
            <tr>
                <th>Date/Time</th>
                <th>Food</th>
                <th>Amount</th>
                <th>Note</th>
                <th>Staff Initials</th>
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
                <tr>
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td> <!-- Ensure this matches the new column name in the database -->
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('carer.carer_menu', unit_name=unit_name, resident_initials=resident_initials) }}" class="btn-dark-green">Back to Menu</a>
{% endblock %}

app/templates/report_personal_care.html
{% extends "base.html" %}

{% block content %}
    <h2>Personal Care Report </h2>
    <h4> for {{ resident_initials }} </h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>Personal Care Type</th>
                <th>Note</th>
                <th>Duration</th>
                <th>Staff Initials</th>
            </tr>
        </thead>
        <tbody>
            {% for record in personal_care_records %}
                <tr>
                    <td>{{ record[0] }}</td>
                    <td>{{ record[1] }}</td>
                    <td>{{ record[2] }}</td>
                    <td>{{ record[3] }}</td>
                    <td>{{ record[4] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('carer.carer_menu', unit_name=unit_name, resident_initials=resident_initials) }}" class="btn-dark-green">Back to Menu</a>
{% endblock %}

app/templates/report_sel.html
{% extends "base.html" %}
{% block content %}
<h1 >hello</h1>

{%endblock%}

app/templates/report_selection.html
{% extends "base.html" %}

{% block content %}
<h2 class="center-text">Report Selection</h2>
<form method="POST" action="{{ url_for('data_output.report_selection') }}" class="form-container" id="report-form">
    <div class="form-group">
        <label for="unit_name">Unit Name:</label>
        <select id="unit_name" name="unit_name" required>
            <option value="">Select Unit</option>
            {% for unit in units %}
                <option value="{{ unit[0] }}">{{ unit[0] }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="resident_initials">Resident:</label>
        <select id="resident_initials" name="resident_initials" required>
            <option value="">Select Resident</option>
            <!-- Residents will be populated dynamically -->
        </select>
    </div>
    <div class="form-group">
        <label for="service_name">Select Report:</label>
        <select id="service_name" name="service_name" required>
            <option value="">Select Report</option>
            {% for service in services %}
                <option value="{{ service[0] }}">{{ service[0] }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="start_date">Start Date:</label>
        <input type="date" id="start_date" name="start_date" value="{{ current_date }}" required>
    </div>
    <div class="form-group">
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" value="{{ current_date }}" required>
    </div>
    <button type="submit">Continue</button>
</form>

<script>
    document.getElementById('unit_name').addEventListener('change', function() {
        var unitName = this.value;
        var residentSelect = document.getElementById('resident_initials');
        
        // Clear current options
        residentSelect.innerHTML = '<option value="">Select Resident</option>';
        
        if (unitName) {
            fetch(`/get_residents?unit_name=${unitName}`)
            .then(response => response.json())
            .then(data => {
                data.residents.forEach(resident => {
                    var option = document.createElement('option');
                    option.value = resident;
                    option.text = resident;
                    residentSelect.add(option);
                });
            })
            .catch(error => console.error('Error fetching residents:', error));
        }
    });
</script>
{% endblock %}
  